//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsGondermeProje3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms/", ConfigurationName="ServiceReference1.smsnn")]
    public interface smsnn {
        
        // CODEGEN: Generating message contract since message part namespace (SMS) does not match the default value (http://sms/)
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_nnRequest", ReplyAction="http://sms/smsnn/sms_gonder_nnResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.sms_gonder_nnResponse sms_gonder_nn(SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_nnRequest", ReplyAction="http://sms/smsnn/sms_gonder_nnResponse")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.sms_gonder_nnResponse> sms_gonder_nnAsync(SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV2Request", ReplyAction="http://sms/smsnn/smsGonderNNV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.smsGonderNNV2Response smsGonderNNV2(SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV2Request", ReplyAction="http://sms/smsnn/smsGonderNNV2Response")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonderNNV2Response> smsGonderNNV2Async(SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV3Request", ReplyAction="http://sms/smsnn/smsGonderNNV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.smsGonderNNV3Response smsGonderNNV3(SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonderNNV3Request", ReplyAction="http://sms/smsnn/smsGonderNNV3Response")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonderNNV3Response> smsGonderNNV3Async(SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_1nRequest", ReplyAction="http://sms/smsnn/sms_gonder_1nResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.sms_gonder_1nResponse sms_gonder_1n(SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/sms_gonder_1nRequest", ReplyAction="http://sms/smsnn/sms_gonder_1nResponse")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.sms_gonder_1nResponse> sms_gonder_1nAsync(SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV2Request", ReplyAction="http://sms/smsnn/smsGonder1NV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.smsGonder1NV2Response smsGonder1NV2(SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV2Request", ReplyAction="http://sms/smsnn/smsGonder1NV2Response")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonder1NV2Response> smsGonder1NV2Async(SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV3Request", ReplyAction="http://sms/smsnn/smsGonder1NV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.smsGonder1NV3Response smsGonder1NV3(SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/smsGonder1NV3Request", ReplyAction="http://sms/smsnn/smsGonder1NV3Response")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonder1NV3Response> smsGonder1NV3Async(SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/krediRequest", ReplyAction="http://sms/smsnn/krediResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.krediResponse kredi(SmsGondermeProje3.ServiceReference1.krediRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/krediRequest", ReplyAction="http://sms/smsnn/krediResponse")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.krediResponse> krediAsync(SmsGondermeProje3.ServiceReference1.krediRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/paketkampanyaRequest", ReplyAction="http://sms/smsnn/paketkampanyaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.paketkampanyaResponse paketkampanya(SmsGondermeProje3.ServiceReference1.paketkampanyaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/paketkampanyaRequest", ReplyAction="http://sms/smsnn/paketkampanyaResponse")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.paketkampanyaResponse> paketkampanyaAsync(SmsGondermeProje3.ServiceReference1.paketkampanyaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporRequest", ReplyAction="http://sms/smsnn/raporResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.raporResponse rapor(SmsGondermeProje3.ServiceReference1.raporRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporRequest", ReplyAction="http://sms/smsnn/raporResponse")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.raporResponse> raporAsync(SmsGondermeProje3.ServiceReference1.raporRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/rapor_v2Request", ReplyAction="http://sms/smsnn/rapor_v2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.rapor_v2Response rapor_v2(SmsGondermeProje3.ServiceReference1.rapor_v2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/rapor_v2Request", ReplyAction="http://sms/smsnn/rapor_v2Response")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.rapor_v2Response> rapor_v2Async(SmsGondermeProje3.ServiceReference1.rapor_v2Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporV3Request", ReplyAction="http://sms/smsnn/raporV3Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.raporV3Response raporV3(SmsGondermeProje3.ServiceReference1.raporV3Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/raporV3Request", ReplyAction="http://sms/smsnn/raporV3Response")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.raporV3Response> raporV3Async(SmsGondermeProje3.ServiceReference1.raporV3Request request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gondericiadlariRequest", ReplyAction="http://sms/smsnn/gondericiadlariResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.gondericiadlariResponse gondericiadlari(SmsGondermeProje3.ServiceReference1.gondericiadlariRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gondericiadlariRequest", ReplyAction="http://sms/smsnn/gondericiadlariResponse")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gondericiadlariResponse> gondericiadlariAsync(SmsGondermeProje3.ServiceReference1.gondericiadlariRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsRequest", ReplyAction="http://sms/smsnn/gelensmsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.gelensmsResponse gelensms(SmsGondermeProje3.ServiceReference1.gelensmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsRequest", ReplyAction="http://sms/smsnn/gelensmsResponse")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gelensmsResponse> gelensmsAsync(SmsGondermeProje3.ServiceReference1.gelensmsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsV2Request", ReplyAction="http://sms/smsnn/gelensmsV2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmsGondermeProje3.ServiceReference1.gelensmsV2Response gelensmsV2(SmsGondermeProje3.ServiceReference1.gelensmsV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sms/smsnn/gelensmsV2Request", ReplyAction="http://sms/smsnn/gelensmsV2Response")]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gelensmsV2Response> gelensmsV2Async(SmsGondermeProje3.ServiceReference1.gelensmsV2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nn", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        public sms_gonder_nnRequest() {
        }
        
        public sms_gonder_nnRequest(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_nnResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_nnResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="SMS", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="SMS")]
        public string @return;
        
        public sms_gonder_nnResponse() {
        }
        
        public sms_gonder_nnResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        public smsGonderNNV2Request() {
        }
        
        public smsGonderNNV2Request(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonderNNV2Response() {
        }
        
        public smsGonderNNV2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("msg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appkey;
        
        public smsGonderNNV3Request() {
        }
        
        public smsGonderNNV3Request(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
            this.appkey = appkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonderNNV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonderNNV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonderNNV3Response() {
        }
        
        public smsGonderNNV3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1n", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        public sms_gonder_1nRequest() {
        }
        
        public sms_gonder_1nRequest(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            this.username = username;
            this.password = password;
            this.company = company;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sms_gonder_1nResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class sms_gonder_1nResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public sms_gonder_1nResponse() {
        }
        
        public sms_gonder_1nResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        public smsGonder1NV2Request() {
        }
        
        public smsGonder1NV2Request(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonder1NV2Response() {
        }
        
        public smsGonder1NV2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("gsm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] gsm;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bayikodu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string appkey;
        
        public smsGonder1NV3Request() {
        }
        
        public smsGonder1NV3Request(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            this.username = username;
            this.password = password;
            this.header = header;
            this.msg = msg;
            this.gsm = gsm;
            this.encoding = encoding;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.bayikodu = bayikodu;
            this.filter = filter;
            this.appkey = appkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="smsGonder1NV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class smsGonder1NV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public smsGonder1NV3Response() {
        }
        
        public smsGonder1NV3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="kredi", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public krediRequest() {
        }
        
        public krediRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="krediResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class krediResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public krediResponse() {
        }
        
        public krediResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanya", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public paketkampanyaRequest() {
        }
        
        public paketkampanyaRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="paketkampanyaResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class paketkampanyaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public paketkampanyaResponse() {
        }
        
        public paketkampanyaResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        public raporRequest() {
        }
        
        public raporRequest(string username, string password, string bulkid, int status, int version) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public raporResponse() {
        }
        
        public raporResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int version;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("telno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] telno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detail;
        
        public rapor_v2Request() {
        }
        
        public rapor_v2Request(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.status = status;
            this.version = version;
            this.telno = telno;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="rapor_v2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class rapor_v2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public rapor_v2Response() {
        }
        
        public rapor_v2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporV3", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporV3Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bulkid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("telno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] telno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string header;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int detail;
        
        public raporV3Request() {
        }
        
        public raporV3Request(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail) {
            this.username = username;
            this.password = password;
            this.bulkid = bulkid;
            this.telno = telno;
            this.header = header;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.type = type;
            this.status = status;
            this.detail = detail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="raporV3Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class raporV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public raporV3Response() {
        }
        
        public raporV3Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlari", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gondericiadlariRequest() {
        }
        
        public gondericiadlariRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gondericiadlariResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gondericiadlariResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gondericiadlariResponse() {
        }
        
        public gondericiadlariResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensms", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public gelensmsRequest() {
        }
        
        public gelensmsRequest(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsResponse", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gelensmsResponse() {
        }
        
        public gelensmsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsV2", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsV2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string startdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stopdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int type;
        
        public gelensmsV2Request() {
        }
        
        public gelensmsV2Request(string username, string password, string startdate, string stopdate, int type) {
            this.username = username;
            this.password = password;
            this.startdate = startdate;
            this.stopdate = stopdate;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="gelensmsV2Response", WrapperNamespace="http://sms/", IsWrapped=true)]
    public partial class gelensmsV2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sms/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public gelensmsV2Response() {
        }
        
        public gelensmsV2Response(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface smsnnChannel : SmsGondermeProje3.ServiceReference1.smsnn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class smsnnClient : System.ServiceModel.ClientBase<SmsGondermeProje3.ServiceReference1.smsnn>, SmsGondermeProje3.ServiceReference1.smsnn {
        
        public smsnnClient() {
        }
        
        public smsnnClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public smsnnClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsnnClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public smsnnClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.sms_gonder_nnResponse SmsGondermeProje3.ServiceReference1.smsnn.sms_gonder_nn(SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest request) {
            return base.Channel.sms_gonder_nn(request);
        }
        
        public string sms_gonder_nn(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest inValue = new SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            SmsGondermeProje3.ServiceReference1.sms_gonder_nnResponse retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).sms_gonder_nn(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.sms_gonder_nnResponse> SmsGondermeProje3.ServiceReference1.smsnn.sms_gonder_nnAsync(SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest request) {
            return base.Channel.sms_gonder_nnAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.sms_gonder_nnResponse> sms_gonder_nnAsync(string username, string password, string company, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest inValue = new SmsGondermeProje3.ServiceReference1.sms_gonder_nnRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).sms_gonder_nnAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.smsGonderNNV2Response SmsGondermeProje3.ServiceReference1.smsnn.smsGonderNNV2(SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request request) {
            return base.Channel.smsGonderNNV2(request);
        }
        
        public string smsGonderNNV2(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            SmsGondermeProje3.ServiceReference1.smsGonderNNV2Response retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonderNNV2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonderNNV2Response> SmsGondermeProje3.ServiceReference1.smsnn.smsGonderNNV2Async(SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request request) {
            return base.Channel.smsGonderNNV2Async(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonderNNV2Response> smsGonderNNV2Async(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonderNNV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonderNNV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.smsGonderNNV3Response SmsGondermeProje3.ServiceReference1.smsnn.smsGonderNNV3(SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request request) {
            return base.Channel.smsGonderNNV3(request);
        }
        
        public string smsGonderNNV3(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            SmsGondermeProje3.ServiceReference1.smsGonderNNV3Response retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonderNNV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonderNNV3Response> SmsGondermeProje3.ServiceReference1.smsnn.smsGonderNNV3Async(SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request request) {
            return base.Channel.smsGonderNNV3Async(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonderNNV3Response> smsGonderNNV3Async(string username, string password, string header, string[] msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonderNNV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonderNNV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.sms_gonder_1nResponse SmsGondermeProje3.ServiceReference1.smsnn.sms_gonder_1n(SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest request) {
            return base.Channel.sms_gonder_1n(request);
        }
        
        public string sms_gonder_1n(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest inValue = new SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            SmsGondermeProje3.ServiceReference1.sms_gonder_1nResponse retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).sms_gonder_1n(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.sms_gonder_1nResponse> SmsGondermeProje3.ServiceReference1.smsnn.sms_gonder_1nAsync(SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest request) {
            return base.Channel.sms_gonder_1nAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.sms_gonder_1nResponse> sms_gonder_1nAsync(string username, string password, string company, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu) {
            SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest inValue = new SmsGondermeProje3.ServiceReference1.sms_gonder_1nRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.company = company;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).sms_gonder_1nAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.smsGonder1NV2Response SmsGondermeProje3.ServiceReference1.smsnn.smsGonder1NV2(SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request request) {
            return base.Channel.smsGonder1NV2(request);
        }
        
        public string smsGonder1NV2(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            SmsGondermeProje3.ServiceReference1.smsGonder1NV2Response retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonder1NV2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonder1NV2Response> SmsGondermeProje3.ServiceReference1.smsnn.smsGonder1NV2Async(SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request request) {
            return base.Channel.smsGonder1NV2Async(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonder1NV2Response> smsGonder1NV2Async(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter) {
            SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonder1NV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonder1NV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.smsGonder1NV3Response SmsGondermeProje3.ServiceReference1.smsnn.smsGonder1NV3(SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request request) {
            return base.Channel.smsGonder1NV3(request);
        }
        
        public string smsGonder1NV3(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            SmsGondermeProje3.ServiceReference1.smsGonder1NV3Response retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonder1NV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonder1NV3Response> SmsGondermeProje3.ServiceReference1.smsnn.smsGonder1NV3Async(SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request request) {
            return base.Channel.smsGonder1NV3Async(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.smsGonder1NV3Response> smsGonder1NV3Async(string username, string password, string header, string msg, string[] gsm, string encoding, string startdate, string stopdate, string bayikodu, int filter, string appkey) {
            SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request inValue = new SmsGondermeProje3.ServiceReference1.smsGonder1NV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.header = header;
            inValue.msg = msg;
            inValue.gsm = gsm;
            inValue.encoding = encoding;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.bayikodu = bayikodu;
            inValue.filter = filter;
            inValue.appkey = appkey;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).smsGonder1NV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.krediResponse SmsGondermeProje3.ServiceReference1.smsnn.kredi(SmsGondermeProje3.ServiceReference1.krediRequest request) {
            return base.Channel.kredi(request);
        }
        
        public string kredi(string username, string password) {
            SmsGondermeProje3.ServiceReference1.krediRequest inValue = new SmsGondermeProje3.ServiceReference1.krediRequest();
            inValue.username = username;
            inValue.password = password;
            SmsGondermeProje3.ServiceReference1.krediResponse retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).kredi(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.krediResponse> SmsGondermeProje3.ServiceReference1.smsnn.krediAsync(SmsGondermeProje3.ServiceReference1.krediRequest request) {
            return base.Channel.krediAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.krediResponse> krediAsync(string username, string password) {
            SmsGondermeProje3.ServiceReference1.krediRequest inValue = new SmsGondermeProje3.ServiceReference1.krediRequest();
            inValue.username = username;
            inValue.password = password;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).krediAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.paketkampanyaResponse SmsGondermeProje3.ServiceReference1.smsnn.paketkampanya(SmsGondermeProje3.ServiceReference1.paketkampanyaRequest request) {
            return base.Channel.paketkampanya(request);
        }
        
        public string paketkampanya(string username, string password) {
            SmsGondermeProje3.ServiceReference1.paketkampanyaRequest inValue = new SmsGondermeProje3.ServiceReference1.paketkampanyaRequest();
            inValue.username = username;
            inValue.password = password;
            SmsGondermeProje3.ServiceReference1.paketkampanyaResponse retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).paketkampanya(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.paketkampanyaResponse> SmsGondermeProje3.ServiceReference1.smsnn.paketkampanyaAsync(SmsGondermeProje3.ServiceReference1.paketkampanyaRequest request) {
            return base.Channel.paketkampanyaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.paketkampanyaResponse> paketkampanyaAsync(string username, string password) {
            SmsGondermeProje3.ServiceReference1.paketkampanyaRequest inValue = new SmsGondermeProje3.ServiceReference1.paketkampanyaRequest();
            inValue.username = username;
            inValue.password = password;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).paketkampanyaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.raporResponse SmsGondermeProje3.ServiceReference1.smsnn.rapor(SmsGondermeProje3.ServiceReference1.raporRequest request) {
            return base.Channel.rapor(request);
        }
        
        public string rapor(string username, string password, string bulkid, int status, int version) {
            SmsGondermeProje3.ServiceReference1.raporRequest inValue = new SmsGondermeProje3.ServiceReference1.raporRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            SmsGondermeProje3.ServiceReference1.raporResponse retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).rapor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.raporResponse> SmsGondermeProje3.ServiceReference1.smsnn.raporAsync(SmsGondermeProje3.ServiceReference1.raporRequest request) {
            return base.Channel.raporAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.raporResponse> raporAsync(string username, string password, string bulkid, int status, int version) {
            SmsGondermeProje3.ServiceReference1.raporRequest inValue = new SmsGondermeProje3.ServiceReference1.raporRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).raporAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.rapor_v2Response SmsGondermeProje3.ServiceReference1.smsnn.rapor_v2(SmsGondermeProje3.ServiceReference1.rapor_v2Request request) {
            return base.Channel.rapor_v2(request);
        }
        
        public string rapor_v2(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            SmsGondermeProje3.ServiceReference1.rapor_v2Request inValue = new SmsGondermeProje3.ServiceReference1.rapor_v2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            inValue.telno = telno;
            inValue.detail = detail;
            SmsGondermeProje3.ServiceReference1.rapor_v2Response retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).rapor_v2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.rapor_v2Response> SmsGondermeProje3.ServiceReference1.smsnn.rapor_v2Async(SmsGondermeProje3.ServiceReference1.rapor_v2Request request) {
            return base.Channel.rapor_v2Async(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.rapor_v2Response> rapor_v2Async(string username, string password, string bulkid, int status, int version, string[] telno, int detail) {
            SmsGondermeProje3.ServiceReference1.rapor_v2Request inValue = new SmsGondermeProje3.ServiceReference1.rapor_v2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.status = status;
            inValue.version = version;
            inValue.telno = telno;
            inValue.detail = detail;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).rapor_v2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.raporV3Response SmsGondermeProje3.ServiceReference1.smsnn.raporV3(SmsGondermeProje3.ServiceReference1.raporV3Request request) {
            return base.Channel.raporV3(request);
        }
        
        public string raporV3(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail) {
            SmsGondermeProje3.ServiceReference1.raporV3Request inValue = new SmsGondermeProje3.ServiceReference1.raporV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.telno = telno;
            inValue.header = header;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            inValue.status = status;
            inValue.detail = detail;
            SmsGondermeProje3.ServiceReference1.raporV3Response retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).raporV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.raporV3Response> SmsGondermeProje3.ServiceReference1.smsnn.raporV3Async(SmsGondermeProje3.ServiceReference1.raporV3Request request) {
            return base.Channel.raporV3Async(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.raporV3Response> raporV3Async(string username, string password, string bulkid, string[] telno, string header, string startdate, string stopdate, int type, int status, int detail) {
            SmsGondermeProje3.ServiceReference1.raporV3Request inValue = new SmsGondermeProje3.ServiceReference1.raporV3Request();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkid = bulkid;
            inValue.telno = telno;
            inValue.header = header;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            inValue.status = status;
            inValue.detail = detail;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).raporV3Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.gondericiadlariResponse SmsGondermeProje3.ServiceReference1.smsnn.gondericiadlari(SmsGondermeProje3.ServiceReference1.gondericiadlariRequest request) {
            return base.Channel.gondericiadlari(request);
        }
        
        public string gondericiadlari(string username, string password) {
            SmsGondermeProje3.ServiceReference1.gondericiadlariRequest inValue = new SmsGondermeProje3.ServiceReference1.gondericiadlariRequest();
            inValue.username = username;
            inValue.password = password;
            SmsGondermeProje3.ServiceReference1.gondericiadlariResponse retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).gondericiadlari(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gondericiadlariResponse> SmsGondermeProje3.ServiceReference1.smsnn.gondericiadlariAsync(SmsGondermeProje3.ServiceReference1.gondericiadlariRequest request) {
            return base.Channel.gondericiadlariAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gondericiadlariResponse> gondericiadlariAsync(string username, string password) {
            SmsGondermeProje3.ServiceReference1.gondericiadlariRequest inValue = new SmsGondermeProje3.ServiceReference1.gondericiadlariRequest();
            inValue.username = username;
            inValue.password = password;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).gondericiadlariAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.gelensmsResponse SmsGondermeProje3.ServiceReference1.smsnn.gelensms(SmsGondermeProje3.ServiceReference1.gelensmsRequest request) {
            return base.Channel.gelensms(request);
        }
        
        public string gelensms(string username, string password) {
            SmsGondermeProje3.ServiceReference1.gelensmsRequest inValue = new SmsGondermeProje3.ServiceReference1.gelensmsRequest();
            inValue.username = username;
            inValue.password = password;
            SmsGondermeProje3.ServiceReference1.gelensmsResponse retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).gelensms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gelensmsResponse> SmsGondermeProje3.ServiceReference1.smsnn.gelensmsAsync(SmsGondermeProje3.ServiceReference1.gelensmsRequest request) {
            return base.Channel.gelensmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gelensmsResponse> gelensmsAsync(string username, string password) {
            SmsGondermeProje3.ServiceReference1.gelensmsRequest inValue = new SmsGondermeProje3.ServiceReference1.gelensmsRequest();
            inValue.username = username;
            inValue.password = password;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).gelensmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGondermeProje3.ServiceReference1.gelensmsV2Response SmsGondermeProje3.ServiceReference1.smsnn.gelensmsV2(SmsGondermeProje3.ServiceReference1.gelensmsV2Request request) {
            return base.Channel.gelensmsV2(request);
        }
        
        public string gelensmsV2(string username, string password, string startdate, string stopdate, int type) {
            SmsGondermeProje3.ServiceReference1.gelensmsV2Request inValue = new SmsGondermeProje3.ServiceReference1.gelensmsV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            SmsGondermeProje3.ServiceReference1.gelensmsV2Response retVal = ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).gelensmsV2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gelensmsV2Response> SmsGondermeProje3.ServiceReference1.smsnn.gelensmsV2Async(SmsGondermeProje3.ServiceReference1.gelensmsV2Request request) {
            return base.Channel.gelensmsV2Async(request);
        }
        
        public System.Threading.Tasks.Task<SmsGondermeProje3.ServiceReference1.gelensmsV2Response> gelensmsV2Async(string username, string password, string startdate, string stopdate, int type) {
            SmsGondermeProje3.ServiceReference1.gelensmsV2Request inValue = new SmsGondermeProje3.ServiceReference1.gelensmsV2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.startdate = startdate;
            inValue.stopdate = stopdate;
            inValue.type = type;
            return ((SmsGondermeProje3.ServiceReference1.smsnn)(this)).gelensmsV2Async(inValue);
        }
    }
}
